package me.lostwizzen.portableworkstations.constants;

public class PortableWorkstationsConstants {

	private PortableWorkstationsConstants() {
	}

	public static final String HEAD_WORKBENCH_BASE64 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWQyYzBjZWRmYzMyZTNiZWVlOTU1Y2FiZDY2ZmQ0ZDc2NWVlZGEzYWRjYzg0YmM0NTFjOWZkYmVjZjNjYjdjMiJ9fX0=";
	
	public static final String TITLE_STONECUTTER = "§6Portable Cutter";
	public static final String HEAD_STONECUTTER_BASE64 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDM5NDlkMGQ4ZjZkOGFlOTEzODUxZmMwMDlkOTQ2MTBjMjFjNDUxZTI3NmU4OWUxOTE2ZjMxYjVhMzY5NzFjIn19fQ==";
//	public static final String HEAD_STONECUTTER_BASE64 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGIyYjYyNGRkYzdkNGE2NWU1MjcwYWU1Yjc3NWUxOGU4ZDU1ODk4ZjE1NzJiNDU5YmRmOTRkZDBkNDY0ODRmNyJ9fX0=";
    
    public static final String TITLE_CARTOGRAPHY = "§6Portable Cartography";
    public static final String HEAD_CARTOGRAPHY_BASE64 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDkwOTdjYTU5MzM0MDIwZTRjMTZkNWJhMzZjYjI0NTgwZWU2NmM5YzJmNDI1YTNiNTY1NGZkYzQ3YjhkYjZmNiJ9fX0=";
    
}
